cc_binary(
    name = "echo",
    srcs = ["echo/main.c"],
    copts = [
        "-Iinclude",
        "-Wall",
        "-Werror",
    ],
    deps = [
        "//include/anhttp",
        "//source:anhttp",
    ],
)
